export const AUTH_LOGIN_ATTEMPT = "AUTH_LOGIN_ATTEMPT"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
export const AUTH_LOGOUT = "AUTH_LOGOUT"